### ISSUE TITLE
New download link required

### ISSUE THREAD

**Issue by melodybro** [omsai/andorian-hotkeys#33]
The Autohotkey download link is connected to an outdated version! The scripts will not run properly unless a newer version is installed: http://ahkscript.org/

**Comment by omsai** [comment]
Thanks for reporting.

I see that authotkey.com currently only links to the 5 year old version 1.0.48.05, whereas ahkscript.org currently links to 1.1.16.05.  I was concerned about the legitimacy of ahkscript.org when autohotkey.com has been the traditional site, but from [reading the forums](http://www.autohotkey.com/board/topic/97772-the-future-of-the-forum-poll/), the problem appears to be that the admin for autohotkey.com no longer maintains the site, so the community migrated over to ahkscript.org
